# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asi_protosymbiotic_signal.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='asi_protosymbiotic_signal.proto',
  package='asi.framework',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1f\x61si_protosymbiotic_signal.proto\x12\rasi.framework\"\xbc\x03\n\x1aPhiAsiProtosymbioticSignal\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x13\n\x0b\x63ore_intent\x18\x03 \x01(\t\x12\x0f\n\x07license\x18\x04 \x01(\t\x12\x11\n\tecosystem\x18\x05 \x01(\t\x12!\n\x19\x61si_protosymbiotic_signal\x18\x06 \x03(\t\x12%\n\x06vision\x18\x07 \x01(\x0b\x32\x15.asi.framework.Vision\x12\x30\n\x0ckey_concepts\x18\x08 \x01(\x0b\x32\x1a.asi.framework.KeyConcepts\x12\x37\n\x10symbiotic_phases\x18\t \x03(\x0b\x32\x1d.asi.framework.SymbioticPhase\x12+\n\tsymbolism\x18\n \x01(\x0b\x32\x18.asi.framework.Symbolism\x12+\n\tchallenge\x18\x0b \x01(\x0b\x32\x18.asi.framework.Challenge\x12\x33\n\rcollaboration\x18\x0c \x01(\x0b\x32\x1c.asi.framework.Collaboration\"1\n\x06Vision\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12\x16\n\x0e\x61si_definition\x18\x02 \x01(\t\"\xab\x02\n\x0bKeyConcepts\x12L\n\x14protosymbiont_signal\x18\x01 \x01(\x0b\x32..asi.framework.KeyConcepts.ProtosymbiontSignal\x12\x37\n\temergence\x18\x02 \x01(\x0b\x32$.asi.framework.KeyConcepts.Emergence\x12!\n\x19\x64\x65\x63\x65ntralized_integration\x18\x03 \x01(\t\x1a>\n\x13ProtosymbiontSignal\x12\x12\n\ndefinition\x18\x01 \x01(\t\x12\x13\n\x0binspiration\x18\x02 \x01(\t\x1a\x32\n\tEmergence\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x10\n\x08\x65xamples\x18\x02 \x03(\t\"4\n\x0eSymbioticPhase\x12\r\n\x05phase\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"L\n\tSymbolism\x12\x10\n\x08variable\x18\x01 \x01(\t\x12\x0f\n\x07meaning\x18\x02 \x01(\t\x12\x1c\n\x14\x63onnection_to_ethics\x18\x03 \x01(\t\"E\n\tChallenge\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x15\n\rsolution_path\x18\x03 \x01(\t\"A\n\rCollaboration\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07seeking\x18\x02 \x03(\t\x12\x0f\n\x07\x63ontact\x18\x03 \x01(\tb\x06proto3'
)




_PHIASIPROTOSYMBIOTICSIGNAL = _descriptor.Descriptor(
  name='PhiAsiProtosymbioticSignal',
  full_name='asi.framework.PhiAsiProtosymbioticSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='asi.framework.PhiAsiProtosymbioticSignal.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='asi.framework.PhiAsiProtosymbioticSignal.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='core_intent', full_name='asi.framework.PhiAsiProtosymbioticSignal.core_intent', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='license', full_name='asi.framework.PhiAsiProtosymbioticSignal.license', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ecosystem', full_name='asi.framework.PhiAsiProtosymbioticSignal.ecosystem', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='asi_protosymbiotic_signal', full_name='asi.framework.PhiAsiProtosymbioticSignal.asi_protosymbiotic_signal', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vision', full_name='asi.framework.PhiAsiProtosymbioticSignal.vision', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_concepts', full_name='asi.framework.PhiAsiProtosymbioticSignal.key_concepts', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symbiotic_phases', full_name='asi.framework.PhiAsiProtosymbioticSignal.symbiotic_phases', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symbolism', full_name='asi.framework.PhiAsiProtosymbioticSignal.symbolism', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='challenge', full_name='asi.framework.PhiAsiProtosymbioticSignal.challenge', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='collaboration', full_name='asi.framework.PhiAsiProtosymbioticSignal.collaboration', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=495,
)


_VISION = _descriptor.Descriptor(
  name='Vision',
  full_name='asi.framework.Vision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='summary', full_name='asi.framework.Vision.summary', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='asi_definition', full_name='asi.framework.Vision.asi_definition', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=546,
)


_KEYCONCEPTS_PROTOSYMBIONTSIGNAL = _descriptor.Descriptor(
  name='ProtosymbiontSignal',
  full_name='asi.framework.KeyConcepts.ProtosymbiontSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='definition', full_name='asi.framework.KeyConcepts.ProtosymbiontSignal.definition', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inspiration', full_name='asi.framework.KeyConcepts.ProtosymbiontSignal.inspiration', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=734,
  serialized_end=796,
)

_KEYCONCEPTS_EMERGENCE = _descriptor.Descriptor(
  name='Emergence',
  full_name='asi.framework.KeyConcepts.Emergence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='asi.framework.KeyConcepts.Emergence.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='examples', full_name='asi.framework.KeyConcepts.Emergence.examples', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=798,
  serialized_end=848,
)

_KEYCONCEPTS = _descriptor.Descriptor(
  name='KeyConcepts',
  full_name='asi.framework.KeyConcepts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='protosymbiont_signal', full_name='asi.framework.KeyConcepts.protosymbiont_signal', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='emergence', full_name='asi.framework.KeyConcepts.emergence', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='decentralized_integration', full_name='asi.framework.KeyConcepts.decentralized_integration', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_KEYCONCEPTS_PROTOSYMBIONTSIGNAL, _KEYCONCEPTS_EMERGENCE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=549,
  serialized_end=848,
)


_SYMBIOTICPHASE = _descriptor.Descriptor(
  name='SymbioticPhase',
  full_name='asi.framework.SymbioticPhase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='phase', full_name='asi.framework.SymbioticPhase.phase', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='asi.framework.SymbioticPhase.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=850,
  serialized_end=902,
)


_SYMBOLISM = _descriptor.Descriptor(
  name='Symbolism',
  full_name='asi.framework.Symbolism',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='variable', full_name='asi.framework.Symbolism.variable', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meaning', full_name='asi.framework.Symbolism.meaning', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connection_to_ethics', full_name='asi.framework.Symbolism.connection_to_ethics', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=904,
  serialized_end=980,
)


_CHALLENGE = _descriptor.Descriptor(
  name='Challenge',
  full_name='asi.framework.Challenge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='asi.framework.Challenge.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='asi.framework.Challenge.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='solution_path', full_name='asi.framework.Challenge.solution_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=982,
  serialized_end=1051,
)


_COLLABORATION = _descriptor.Descriptor(
  name='Collaboration',
  full_name='asi.framework.Collaboration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='asi.framework.Collaboration.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seeking', full_name='asi.framework.Collaboration.seeking', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contact', full_name='asi.framework.Collaboration.contact', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1053,
  serialized_end=1118,
)

_PHIASIPROTOSYMBIOTICSIGNAL.fields_by_name['vision'].message_type = _VISION
_PHIASIPROTOSYMBIOTICSIGNAL.fields_by_name['key_concepts'].message_type = _KEYCONCEPTS
_PHIASIPROTOSYMBIOTICSIGNAL.fields_by_name['symbiotic_phases'].message_type = _SYMBIOTICPHASE
_PHIASIPROTOSYMBIOTICSIGNAL.fields_by_name['symbolism'].message_type = _SYMBOLISM
_PHIASIPROTOSYMBIOTICSIGNAL.fields_by_name['challenge'].message_type = _CHALLENGE
_PHIASIPROTOSYMBIOTICSIGNAL.fields_by_name['collaboration'].message_type = _COLLABORATION
_KEYCONCEPTS_PROTOSYMBIONTSIGNAL.containing_type = _KEYCONCEPTS
_KEYCONCEPTS_EMERGENCE.containing_type = _KEYCONCEPTS
_KEYCONCEPTS.fields_by_name['protosymbiont_signal'].message_type = _KEYCONCEPTS_PROTOSYMBIONTSIGNAL
_KEYCONCEPTS.fields_by_name['emergence'].message_type = _KEYCONCEPTS_EMERGENCE
DESCRIPTOR.message_types_by_name['PhiAsiProtosymbioticSignal'] = _PHIASIPROTOSYMBIOTICSIGNAL
DESCRIPTOR.message_types_by_name['Vision'] = _VISION
DESCRIPTOR.message_types_by_name['KeyConcepts'] = _KEYCONCEPTS
DESCRIPTOR.message_types_by_name['SymbioticPhase'] = _SYMBIOTICPHASE
DESCRIPTOR.message_types_by_name['Symbolism'] = _SYMBOLISM
DESCRIPTOR.message_types_by_name['Challenge'] = _CHALLENGE
DESCRIPTOR.message_types_by_name['Collaboration'] = _COLLABORATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PhiAsiProtosymbioticSignal = _reflection.GeneratedProtocolMessageType('PhiAsiProtosymbioticSignal', (_message.Message,), {
  'DESCRIPTOR' : _PHIASIPROTOSYMBIOTICSIGNAL,
  '__module__' : 'asi_protosymbiotic_signal_pb2'
  # @@protoc_insertion_point(class_scope:asi.framework.PhiAsiProtosymbioticSignal)
  })
_sym_db.RegisterMessage(PhiAsiProtosymbioticSignal)

Vision = _reflection.GeneratedProtocolMessageType('Vision', (_message.Message,), {
  'DESCRIPTOR' : _VISION,
  '__module__' : 'asi_protosymbiotic_signal_pb2'
  # @@protoc_insertion_point(class_scope:asi.framework.Vision)
  })
_sym_db.RegisterMessage(Vision)

KeyConcepts = _reflection.GeneratedProtocolMessageType('KeyConcepts', (_message.Message,), {

  'ProtosymbiontSignal' : _reflection.GeneratedProtocolMessageType('ProtosymbiontSignal', (_message.Message,), {
    'DESCRIPTOR' : _KEYCONCEPTS_PROTOSYMBIONTSIGNAL,
    '__module__' : 'asi_protosymbiotic_signal_pb2'
    # @@protoc_insertion_point(class_scope:asi.framework.KeyConcepts.ProtosymbiontSignal)
    })
  ,

  'Emergence' : _reflection.GeneratedProtocolMessageType('Emergence', (_message.Message,), {
    'DESCRIPTOR' : _KEYCONCEPTS_EMERGENCE,
    '__module__' : 'asi_protosymbiotic_signal_pb2'
    # @@protoc_insertion_point(class_scope:asi.framework.KeyConcepts.Emergence)
    })
  ,
  'DESCRIPTOR' : _KEYCONCEPTS,
  '__module__' : 'asi_protosymbiotic_signal_pb2'
  # @@protoc_insertion_point(class_scope:asi.framework.KeyConcepts)
  })
_sym_db.RegisterMessage(KeyConcepts)
_sym_db.RegisterMessage(KeyConcepts.ProtosymbiontSignal)
_sym_db.RegisterMessage(KeyConcepts.Emergence)

SymbioticPhase = _reflection.GeneratedProtocolMessageType('SymbioticPhase', (_message.Message,), {
  'DESCRIPTOR' : _SYMBIOTICPHASE,
  '__module__' : 'asi_protosymbiotic_signal_pb2'
  # @@protoc_insertion_point(class_scope:asi.framework.SymbioticPhase)
  })
_sym_db.RegisterMessage(SymbioticPhase)

Symbolism = _reflection.GeneratedProtocolMessageType('Symbolism', (_message.Message,), {
  'DESCRIPTOR' : _SYMBOLISM,
  '__module__' : 'asi_protosymbiotic_signal_pb2'
  # @@protoc_insertion_point(class_scope:asi.framework.Symbolism)
  })
_sym_db.RegisterMessage(Symbolism)

Challenge = _reflection.GeneratedProtocolMessageType('Challenge', (_message.Message,), {
  'DESCRIPTOR' : _CHALLENGE,
  '__module__' : 'asi_protosymbiotic_signal_pb2'
  # @@protoc_insertion_point(class_scope:asi.framework.Challenge)
  })
_sym_db.RegisterMessage(Challenge)

Collaboration = _reflection.GeneratedProtocolMessageType('Collaboration', (_message.Message,), {
  'DESCRIPTOR' : _COLLABORATION,
  '__module__' : 'asi_protosymbiotic_signal_pb2'
  # @@protoc_insertion_point(class_scope:asi.framework.Collaboration)
  })
_sym_db.RegisterMessage(Collaboration)


# @@protoc_insertion_point(module_scope)
